### ISSUE TITLE
Last question for the AQL query is missing "condition" part

### ISSUE THREAD

**Issue by vanessa-pereira** [gmickel/openehr-quest#1]
Hi! Thanks for building this quest, it's great!
In the last question you have the query do get all BP readings from people who have hypertension over the last year, but it's missing the filtering per condition/diagnosis.

Here is the corrected AQL (assuming problem/diagnosis archetype is the one meant for this use):

`SELECT 
       e/ehr_id/value as ehr_id,
       p/data[at0001]/items[at0002]/value AS diagnosis,
       o/data[at0001]/events[at0006]/data[at0003]/items[at0004]/value AS systolic,
       o/data[at0001]/events[at0006]/data[at0003]/items[at0005]/value AS diastolic
FROM EHR e 
CONTAINS COMPOSITION c 
CONTAINS OBSERVATION o[openEHR-EHR-OBSERVATION.blood_pressure.v1] 
CONTAINS EVALUATION p[openEHR-EHR-EVALUATION.problem_diagnosis.v1] 
WHERE c/context/start_time > current_date - P1Y AND diagnosis='hypertension'
ORDER BY c/context/start_time DESC`

I am looking forward to participating in more quests!

**Comment by gmickel** [comment]
Thanks so much for your insightful feedback! This is exactly why I love open source - this kind of detailed, expert input is invaluable for improving the educational aspect of the game. 

I threw this game together pretty quickly as a fun way to learn about OpenEHR, and contributions like yours really help!

I've updated the game with your more accurate query, and expanded the explanation to highlight the importance of combining different clinical concepts in AQL queries.
