### ISSUE TITLE
Allow both XML and JSON as correct answers

### ISSUE THREAD

**Issue by ErikSundvall** [gmickel/openehr-quest#7]
See problem description in https://discourse.openehr.org/t/interactive-quiz-game-to-learn-openehr-concepts/5486/9?u=erik.sundvall regarding the question https://github.com/gmickel/openehr-quest/blob/main/src/questions/the-integration-inquisitor.md

Does the program allow to have two correct answers? If so add XML as correct, if not refomulate alternatives.

**Comment by gmickel** [comment]
Thank you, @ErikSundvall , for bringing this to my attention. I'll look into implementing support for multiple correct answers in the upstream project at https://github.com/gmickel/CodeQuest. Once that's done, I'll merge the changes into this OpenEHR quiz to allow for both correct answers. Appreciate your input in improving the quiz!

**Comment by gmickel** [comment]
Everything should now work. It should allow both answers and display both answers as being correct. Thanks again!
